### ISSUE TITLE
Creating or updating a server has a missing steamcmd argument

### ISSUE THREAD

**Issue by MedGR450** [n0tic/SteamServerCreationTool#6] opened 2021-11-24 03:06 UTC
**Description:**
Trying to create or update a server will always result in a "Please use force_install_dir before login!" error.

**Steps to reproduce the behavior:**
1. Choose "Manage Servers"
2. Choose server and click on "Update Select Server"
3. Confirm the warning
4. Wait for some commands to be passed
5. Error pops up and the cmd closes

**Expected behavior**
Steamcmd starts updating/verifying server files.

**Screenshots**
![image](https://user-images.githubusercontent.com/22678541/143159822-ff3a06d9-71c9-4b14-b890-59a587be2626.png)

**Desktop:**
 - .NET Version 6.0
 - Windows Server 2022 21H2 Build Version (eg 20348.350)

**Comment by n0tic** [comment] 2021-11-24 05:38
I have updated the template to require server information as well.

In order to debug this I need to know:
What server are we trying to update/Install?
Have you successfully installed any other server or does all fail?
At what location is this server installed?

I don't seem to be able to replicate this bug with any server.
In order to find a solution, I need your help.

Thank you for letting me know of this bug!

**Comment by MedGR450** [comment] 2021-11-24 07:29
> What server are we trying to update/Install?
Tried Satisfactory and Myth of Empires, same result.
> Have you successfully installed any other server or does all fail?
Space Engineers server got installed successfully, but I still had that yellow error (server install and usage is 100% successful)
>At what location is this server installed?
Microsoft Azure Windows Server 2022, install folder is in F:/Game_Servers

And since you can't replicate it, it might have something to do with a different configuration/implementation on my server, but still it's an untouched fresh install of Win Server 2022.

Thanks for Looking into this!

**Comment by n0tic** [comment] 2021-11-24 18:20
I have done some research about this issue and found that this is most likely caused by an update to SteamCMD itself.
There are very little information about this update and the SteamCMD wiki hasn't yet been updated.

Wiki was last updated:
_This page was last edited on 12 September 2020, at 18:50._

However, even with this error present in the console the installs/updates seem to be working without issues.
Can you confirm that your installs/updates work even with the error present?

I will keep an eye on this and update as soon as possible.
As of right now, SteamCMD "crashes" if I I run force_install_dir before logon. 

Thanks for your interest in my application. Enjoy =)

**Comment by MedGR450** [comment] 2021-11-25 07:11
> 
Thanks for the reply,

I can confirm that the other servers are working and installing even with that error present. I changed some administrator settings on the server and it seems it's fixed. Satisfactory, Space Engineers, 7 Days to Die and Astroneer servers were installed successfully.
The only issue is with the recent Myth of Empires server, shows "no subscription" even though the dedicated server is public (doesn't require a logged-in account) and is listed on SSCT. But it might be because of Steam content servers since the game is still new.

![image](https://user-images.githubusercontent.com/22678541/143395633-902d0a68-21c5-410b-99a4-7eb7a1a0ba7b.png)

**Comment by n0tic** [comment] 2021-11-25 15:58
The game may require you to own the game and setup the server to use your (personal?) steam account.
If this is the case I couldn't say but my application allows for login in settings - You will need to experiment.

### Results from SteamCMD Wiki:
**"Failed to install app 'xxxxxx' (No subscription)"**
If you get the 'No subscription' error, the game/server you are trying to download either requires a login or that you have purchased the game. 

**Note: For security reasons it is recommended that you create a new Steam account just for your dedicated servers.**

Thanks! Closing issue.

**Closed by n0tic** 2021-11-25 15:58 UTC
